#define SECRET_WIFI_NAME "622 lau 3.1"
#define SECRET_WIFI_PASSWORD "68686868"

#define MQTT_BROKER_SERVER_IP "mqtt3.thingspeak.com"

#define SECRET_MQTT_USERNAME "FgAoBTggIjEHMAINNhshOwg"
#define SECRET_MQTT_PASSWORD "n+Ape91KEhJ4NlUXBWg7BoIj"
#define SECRET_MQTT_CLIENT_ID "FgAoBTggIjEHMAINNhshOwg"
#define CHANNEL_ID "2308807"
